Merge
yanisderbikov/vizhuonline pull request #4
Opened 2024-03-16 06:41 UTC by yanisderbikov

Выполненные задачи: 

1. разработан каркас приложения
2. добавлена авторизация через SpringSecurity
3. разработан сервис для аунтефикации через JWT-токен. (signup/signin, но валидация пока что работает не верно)

2024-03-19 12:43 UTC, yanisderbikov commented
Все замечания были учтены

2024-03-20 16:59 UTC, traktorlixach commented on .env.dist
> +DATABASE_URL="jdbc:postgresql://localhost..."
порт?

2024-03-20 16:59 UTC, traktorlixach commented on .env.dist
> +
порт?

2024-03-20 16:59 UTC, traktorlixach commented on .gitignore
> -.vscode/
А зачем удалил? думаю, может понадобиться и мне, и другим разработчикам

2024-03-20 16:59 UTC, traktorlixach commented on README.md
> +```node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"``` вставкой в поле [token.secret.key](src/main/resources/application.properties)
у меня не получилось.. Command 'node' not found

2024-03-20 16:59 UTC, traktorlixach commented on README.md
> +где находится docker-compose. ([пример для файла .env](.env.dist))
в одну строку можно написать
и поправь, плиз, "в том же", и запятую после этого

2024-03-20 16:59 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/config/SeedDataConfig.java
> +                    .email("admin@admin.com")
Предлагаю использовать строковые одинарные кавычки для строк

2024-03-20 16:59 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/config/SeedDataConfig.java
> +public class SeedDataConfig implements CommandLineRunner {
А зачем нужен этот класс?

2024-03-20 16:59 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +    public AuthenticationProvider authenticationProvider(){
{ с новой строки

2024-03-20 16:59 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +    public AuthenticationManager authenticationManager(AuthenticationConfiguration config) throws Exception{
{ с новой строки  
здесь и везде в проекте, и в классах и в методах

2024-03-20 16:59 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +                .csrf(AbstractHttpConfigurer::disable)
слишком большой отступ, должно быть на три пробела меньше

2024-03-20 16:59 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +        return authProvider;
пустая строка перед возвратом

2024-03-20 16:59 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/controller/AuthenticationController.java
> +    @PostMapping("/signup")
строки в одинарных кавычках

2024-03-20 16:59 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +public class WebSecurityConfig {
{ с новой строки

2024-03-20 16:59 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +                        .requestMatchers(HttpMethod.POST, "/api/v1/signup", "/api/v1/signin").permitAll() // no sec
Что за коммент справа? он не добавляет ясности
Нужно переписать код так, чтобы комментарий был не нужен, либо переписать коммент

2024-03-20 16:59 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/controller/UserCommandController.java
> + */
Коммент избыточен, имя класса и так красноречиво. И в классе ниже тоже

2024-03-20 16:59 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/exceptions/infrastructure/DatabaseException.java
> +    public DatabaseException(String message, Throwable cause) {
пустая строка нужна

2024-03-26 10:39 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +    public AuthenticationManager authenticationManager(AuthenticationConfiguration config) throws Exception{
В [Google Java Style](https://google.github.io/styleguide/javaguide.html#s3.4-class-declaration), который мы договорились использовать, начальная скобка не уходит на новую строчку
`return new MyClass() {
  @Override public void method() {
    if (condition()) {
      try {
        something();
      } catch (ProblemException e) {
        recover();
      }
    } else if (otherCondition()) {
      somethingElse();
    } else {
      lastThing();
    }
    {
      int x = foo();
      frob(x);
    }
  }
};`

2024-03-26 11:00 UTC, yanisderbikov commented
Рефакторинг класса User и расширение модели доменов

- Класс User теперь абстрактный, служит базовым классом для Client, Taroter и Staff.
- Удалены поля: lastName, createdAt и role из класса User.
- Добавлено поле uuid в класс User для уникальной идентификации экземпляров.
- Поле email переименовано в login для большей ясности и единообразия в моделях.
- Введены классы Client, Taroter и Staff, наследующие от абстрактного класса User, что заложило основу для атрибутов и поведения, специфичных для домена.
- Создан интерфейс Timestampable с методами getCreatedAt и getUpdatedAt для отслеживания временных меток сущности.
- Реализован абстрактный класс TimestampableEntity для инкапсуляции общего поведения временных меток, класс User расширен этим абстрактным классом для наследования возможностей работы с временными метками.
- Исправлен UserService 
- Другие замечания 

Эти изменения упрощают дизайн сущности User, делая его более адаптируемым для будущих улучшений и более соответствующим эволюционирующей модели домена проекта.

2024-03-27 13:16 UTC, traktorlixach requested changes

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/controller/AuthenticationController.java
> +    @PostMapping("/signin")
давай login, как антипод logout'у

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/controller/HomeController.java
> +        return "redirect:https://vizhu.online";
Домен вынести в переменные окружения

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/controller/TestController.java
> +public class TestController {
Для чего этот контроллер?

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/controller/UserCommandController.java
> +    @PutMapping("/update")
как будет выглядеть полный путь эндпоинта этого метода?

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/dto/SignInRequest.java
> +}
Переименовать в LoginRequest, email -> login

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/dto/SignUpRequest.java
> +    private String lastName;
lastName уйдёт

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/dto/SignUpRequest.java
> +public class SignUpRequest extends SignInRequest{
Почему запрос на регистрацию зависит от запроса на авторизацию? Это же разные контексты

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/exceptions/application/BaseApplicationException.java
> +public abstract class BaseApplicationException extends RuntimeException {
Слово `Base` лучше убрать из названия класса (здесь и ниже), потому что и так понятно, что он базовый, из названия и абстрактности

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/exceptions/infrastructure/DatabaseException.java
> + */
Коммент избыточен

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/filters/JwtAuthenticationFilter.java
> +                                   @NonNull FilterChain filterChain) throws ServletException, IOException{
{ с новой строки

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/filters/JwtAuthenticationFilter.java
> +        final String userEmail;
чем обусловлено то, что где-то ты пишешь переменным `final` или `var`, а где-то не пишешь?

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/filters/JwtAuthenticationFilter.java
> +                log.debug("User = " + userDetails);
Все дебажные сообщения нужно убрать на этапе пуша коммита

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/filters/JwtAuthenticationFilter.java
> +            if (jwtService.isTokenValid(jwt, userDetails)){
Форматирование отсутствует от слова совсем

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/model/User.java
> +    public String getPassword() {
Очень небезопасно делать такой метод публичным. Зачем он? Чтобы проверить пароль с вводимым? Для этого нужно проверить его инкапсулированно, не выдавая пароль внешним классам. Максимум сделать protected, если пароль будет проверять какая-то обёртка над юзером. Подумай на реализацией или давай обсудим

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/model/User.java
> +    }
Зачем все эти методы? У нас нет функционала для них

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/model/User.java
> +        return true;
Кажется, метод на будущее, давай оставим, но будет отдавать поле из модели

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/model/User.java
> +
Лишняя строка

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/AuthenticationService.java
> +public class AuthenticationService {
Ты же для юзером делал Query и Command сервисы, а тут не так же будет?

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/AuthenticationService.java
> +        return JwtAuthenticationResponse.builder().token(jwt).build();
Тут происходит несколько вещей:
- создаётся юзер
- сохраняется юзер
- генерируется токен на основе юзера
- генерируется и отдаётся ответ с токеном

Это разные ответственности, которые должны выполнять соответствующие сервисы, а не всё в одном методе.
Первые два пункта должен делать userServiceCommand, приняв DTO и отдав юзера. А потом нужно дать какому-то сервису этого юзера, чтобы тот вернул токен. Третьим шагом - передать токен в приватный метод текущего класса, а тот вернёт JwtAuthenticationResponse. Таким образом метод будет в три строки и не будет делать то, чего вообще не должен)

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/AuthenticationService.java
> +    }
Аналогично методу выше подлежит переписыванию, а юзер будет искаться по логину, не по мылу

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/JwtService.java
> +    public String generateToken(UserDetails userDetails) {
Что за класс/интерфейс UserDetails? Не вижу его у тебя в коде. Кажется, он имеет намного больше, чем мы будем использовать, и это вносит ряд ненужных зависимостей

2024-03-27 13:16 UTC, traktorlixach commented on src/main/resources/application.properties
> +token.expiration.ms=3600000
Нужна пустая строка в конце

2024-03-27 13:16 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +    public AuthenticationManager authenticationManager(AuthenticationConfiguration config) throws Exception{
окей, давай так пока

2024-03-27 13:21 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +    public AuthenticationManager authenticationManager(AuthenticationConfiguration config) throws Exception{
окей, давай так пока

2024-03-28 10:41 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/controller/TestController.java
> +public class TestController {
Этот контроллер помогает определить корректно ли работает JWT токен. Скорее всего в проду он не нужен, верно?

2024-03-28 10:42 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/controller/UserCommandController.java
> +    @PutMapping("/update")
```
@RequestMapping("/api/v1")
public class UserCommandController {
    private final UserServiceCommand userService;

    @PutMapping("/update")
    public ResponseEntity<UserDtoResponse> updateUser(@Valid @RequestBody SignUpRequest request){
```

Стоится из двух @RequestMapping("/api/v1") и @PutMapping("/update") , получается /api/v1/update

2024-03-28 10:45 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/dto/SignUpRequest.java
> +    private String lastName;
Тогда стоит заменить на name?

2024-03-28 10:48 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/dto/SignUpRequest.java
> +public class SignUpRequest extends SignInRequest{
Согласен. В данном решении просто уменьшение количества строчек. 
Логика такая, что бы зарегистрироваться всеравно нужны поля, такие как login и password. 

Сомневался в решении, спасибо, что подсказал

2024-03-28 10:51 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/filters/JwtAuthenticationFilter.java
> +        final String userEmail;
final просто для того чтобы указать, что поле неизменчиво. 
var - может быть изменено.

2024-03-28 12:38 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/service/AuthenticationService.java
> +        return JwtAuthenticationResponse.builder().token(jwt).build();
Отличное замечание, исправил. 
Я правда добавил в DTO опциональный параметр Role 
То есть можно будет зарегаться как просто клиент 
```
{
    "username": "user",
    "login": "user@user.com",
    "password": "password"
}
```
Либо с указанием кто по должности, чтобы можно было зарегаться как Staff или Taroter
```
{
    "username": "user",
    "role": "ADMIN", // или Taroter
    "login": "user@user.com",
    "password": "password"
}
```

2024-03-28 12:43 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/service/AuthenticationService.java
> +    }
Заменил вот так, на сколько верно?
я думаю на другой класс скидывать задачу аунификации ( _authenticate_  ) нет смысла ?
```
public JwtAuthenticationResponse login(LoginRequest request) {
        authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(request.getLogin(), request.getPassword()));
        var user = userServiceQuery.findByLogin(request.getLogin());
        var jwt = jwtService.generateToken(user);
        return generate(jwt);
    }
```

2024-03-28 12:55 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/controller/TestController.java
> +public class TestController {
Да, и на тестовом окружении JWT тоже должен работать, для него свои ключи можно сгенерить

2024-03-28 13:00 UTC, yanisderbikov commented
Выполнено: 
- api/v1/signup -> api/v1/login
- редирект HomeController вынесен в аргументы окружения
- SignInRequest.email -> login
- JwtAuthenticationResponse изменена архитектура, часть делегирована
- User не реализует интерфейс UserDetails, вынесено в CustomUserDetailsService
- User.password скрыт на protected

2024-03-28 13:34 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/controller/UserCommandController.java
> +    @PutMapping("/update")
Тогда предлагаю вынести "/api/v1" в отдельный мапинг для всех контроллеров, если это возможно. А для RequestMapping необходимо упоминание слова user, а то из "/api/v1/update" неясно, чего мы апдейтим)

2024-03-28 13:44 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/AuthenticationService.java
> +    }
Поясни, что делает authenticationManager.authenticate? Если он необходим, то `new UsernamePasswordAuthenticationToken` нужно вынести в приватный метод, обращайся к нему для authenticationManager.authenticate  

Последние две строчки метода как будто занимаются генерацией токена, может их вынести в отдельный приватный метод? И что на самом деле делает функция generate()?

Ну и отступ пустой строкой перед return не забудь

2024-03-28 14:29 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/controller/UserCommandController.java
> +    @PutMapping("/update")
То есть в конечном счете сделать /api/v1/user/update?
Я вообще думал, кем это будет использоваться? Может быть стоит сделать как /api/v1/update/{id} ?

2024-03-28 14:42 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/controller/AuthenticationController.java
> +    @PostMapping("/signup")
Одинарные ковычки с точки зрения Java - не очень логично, в моем понимании. Это же строка, а строки как правило указывают в двойных. 

И если указать одинарные, то IDE ругается

2024-03-28 14:46 UTC, yanisderbikov commented on .gitignore
> -.vscode/
Честно как-то не уследил. Просто мне не нужен был.

2024-03-28 14:49 UTC, yanisderbikov commented on README.md
> +```node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"``` вставкой в поле [token.secret.key](src/main/resources/application.properties)
Нужен node.js, На самом деле же без разницы какой метод использовать секретный ключ. Можно самостоятельно написать HelloWorld :) . 

Или лучше написать как установить node.js и тп?

2024-03-28 14:54 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/config/SeedDataConfig.java
> +                    .email("admin@admin.com")
В Java невозможно использовать одинарные кавычки. В одинарных кавычках только тип char

2024-03-28 14:55 UTC, traktorlixach commented on README.md
> +```node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"``` вставкой в поле [token.secret.key](src/main/resources/application.properties)
Да, я к этому же)  
Стороннему разработчику (мне например) не нужно знать детали окружения, чтобы работать с кодом.  
Инструкция должна быть полной или отсутствовать

2024-03-28 14:56 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/controller/TestController.java
> +public class TestController {
По-итогу оставляем или нет?)

2024-03-28 14:58 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/controller/AuthenticationController.java
> +    @PostMapping("/signup")
Понял, сорян, я думал, что двойные - это интерпретирующие переменные. В Java одинарные только для символов (char)

2024-03-28 14:59 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/model/User.java
> +    public String getPassword() {
По-итогу я сделал protected, но пришлось перенести CustomUserDetailsService в директорию repo, хотя он должен находиться в service. На сколько это приемлемо?

2024-03-28 14:59 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/model/User.java
> +        return true;
Пока что убрал, когда нужно будет, вернем.

2024-03-28 15:14 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/service/JwtService.java
> +    public String generateToken(UserDetails userDetails) {
Я скрыл немного UserDetails этот интерфейс нужен будет для реализации Фитч по типу: 
_Set<GrantedAuthority> authorities // Роли
accountNonExpired
accountNonLocked
credentialsNonExpired_

2024-03-28 15:20 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/controller/UserCommandController.java
> +    @PutMapping("/update")
Да, /api/v1/user/update  
Вообще надо сделать его POST, у нас будут только методы запросов (Query) и методы команд (Command). Команды включают в себя любые изменения. Так вот запросы - GET, а команды - POST. Все данные для них передаются соответственно в URI для GET или в теле запроса для POST

Также мы будем придерживаться методологии BFF (Backend For Frontend), поэтому этот метод будет ещё изменён - update неясно что изменяет и какую задачу реализует, а вот POST /api/v1/change-password весьма красноречиво. Так лучше, потому что редко вообще кому-то нужно изменить всё сразу в пользователе, а отдельными методами легко разделить ответственность команд и гарантировать изоляцию с точки зрения правок и логики взаимодейстсвия с фронтом, например

2024-03-28 15:23 UTC, traktorlixach commented on .gitignore
> -.vscode/
Верни в рамках необходимого, пожалуйста, будем править по ходу разработки ещё

2024-03-28 15:26 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/JwtService.java
> +    public String generateToken(UserDetails userDetails) {
Я эти методы видел, но что они делают? Пока выглядят избыточными

2024-03-28 15:28 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/controller/TestController.java
> +public class TestController {
Контроллер удаляем, инструкцию для настройки JWT локально - добавляем)

2024-03-28 15:40 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/service/AuthenticationService.java
> +    }
authenticationManager.authenticate это часть SpringSecurity. Помагает для генерации JWT токена. 

```
public class AuthenticationService {

    private final UserServiceCommand userServiceCommand;
    private final UserServiceQuery userServiceQuery;
    private final JwtService jwtService;
    private final AuthenticationManager authenticationManager;

    public JwtAuthenticationResponse signup(SignUpRequest request) {
        var user = userServiceCommand.createUser(request);
        return generate(user);
    }

    public JwtAuthenticationResponse login(LoginRequest request) {
        auth(request);
        var user = userServiceQuery.findByLogin(request.getLogin());
        return generate(user);
    }

    private JwtAuthenticationResponse generate(User user) {
        var jwt = jwtService.generateToken(user);
        return JwtAuthenticationResponse.builder().token(jwt).build();
    }
    
    private void auth(LoginRequest request){
        authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(request.getLogin(), request.getPassword()));
    }
}
```

Такая реализация?

2024-03-28 15:46 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/service/JwtService.java
> +    public String generateToken(UserDetails userDetails) {
Да, согласен, что они сейчас они избыточны. 

Основаная задача это проверка по Ролям. authorities. И позволяет SpringSecurity проверять/обратаывать jwt и остальные Фитчи.

2024-03-28 15:51 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/controller/TestController.java
> +public class TestController {
Что значит  _инструкцию для настройки JWT локально  - добавляем_, . 
Это что-то вроде статичного JWT? не очень понял концепцию

2024-03-28 15:57 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/service/AuthenticationService.java
> +public class AuthenticationService {
Не понял. Проверь с новым коммитом. Вроде все хорошо должно быть

2024-03-28 16:02 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +        return authProvider;
Я отформатировал по Google Style, вроде тут все корректно

2024-03-28 16:04 UTC, yanisderbikov commented on .env.dist
> +
Исправил

2024-03-28 16:11 UTC, yanisderbikov commented on README.md
> +```node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"``` вставкой в поле [token.secret.key](src/main/resources/application.properties)
Исправил

2024-03-28 16:14 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +                        .requestMatchers(HttpMethod.POST, "/api/v1/signup", "/api/v1/signin").permitAll() // no sec
Исправил

2024-03-28 16:14 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/controller/UserCommandController.java
> + */
Исправил

2024-03-28 16:14 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/exceptions/infrastructure/DatabaseException.java
> +    public DatabaseException(String message, Throwable cause) {
Исправил

2024-03-28 16:17 UTC, yanisderbikov commented on README.md
> +где находится docker-compose. ([пример для файла .env](.env.dist))
Поправил по автоматическому форматированию

2024-03-29 04:18 UTC, traktorlixach commented
Откомментил в тредах

2024-03-29 04:20 UTC, traktorlixach requested changes

2024-03-29 04:20 UTC, traktorlixach commented on .env.dist
> +
А где? переменной порта нет

2024-03-29 04:20 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/controller/TestController.java
> +public class TestController {
Для работы JWT на тестовом стенде или локальной разработке нужны какие-то настройки, наверное. Как сервер приложения в докер-контейнере сможет валидировать токен пользователя? Или если я разверну проект как описано в инструкции, то всё заработает из коробки?

2024-03-29 04:20 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/AuthenticationService.java
> +public class AuthenticationService {
Для пользователей сервис команд называется UserServiceCommand, а для аутентификатора просто AuthenticationService без Command, хотя тоже работает с контроллером. Почему так?

2024-03-29 04:20 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/AuthenticationService.java
> +    }
authenticationManager.authenticate не нужно выносить. Нужно вынести `new UsernamePasswordAuthenticationToken` - для разделения ответственности. Создание объектов - это априори отдельная ответственность и в данном случае она не связана с процессом генерации JWT  

Вообще в классе какая-то путаница, сложно понять что происходит. Кажется, что нужно просто найти/создать юзера (за это должен полностью отвечать userServiceCommand) и сгенерировать JWT токен (тут неясно кто за это отвечает, потому что есть JwtService и AuthenticationManager). Вынеси JwtService и AuthenticationManager в новый класс, который будет отвечать за выдачу и проверку токенов, например. А методы auth и generate перенеси в него же, тут к ним нужно только обращаться

2024-03-29 04:20 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/JwtService.java
> +    public String generateToken(UserDetails userDetails) {
Что такое Фитчи?) 
Если что-то избыточно, то нужно удалить. Если это невозможно удалить из-за зависимости, то надо удалить зависимость. Если она необходима для чего-то ещё, то поясни, плиз. Может это "нужное что-то" можно реализовать без зависимостей от того, что на не нужно

2024-03-29 05:12 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +        return authProvider;
Давай мы в некоторых местах отойдём от стандарта во благо удобочитаемости, перед return лучше отступать строку для отделения его от логики метода (исключение - если return идёт в начале метода). Приведи так все методы, пожалуйста

2024-03-29 06:07 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/controller/UserCommandController.java
> +    @PutMapping("/update")
Правки: 
- UserCommandController имеет теперь 2 метода 
  - /api/v1/user/change-password с телом запроса login, password, newPassword. 
  - /api/v1/user/change-username c телом запроса login, password, newUserName.
  
Вопрос такой. Изменение данных каких-то должно быть валидировано паролем или нет? То есть, нужно ли вообще как-то проверять пароль? Пока что пароль никак не проверяется. То есть доступно изменение грубо говоря каждому пользователю.

2024-03-29 07:14 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +        return authProvider;
Сделал, но мне, честно так не очень понравилось, как выглядит.

2024-03-29 07:16 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/service/AuthenticationService.java
> +public class AuthenticationService {
Изменил на имя AuthenticationServiceCommand, все верно?

2024-03-29 07:38 UTC, yanisderbikov commented on .env.dist
> +
Порт указывается полноценно в адресе. Так-же там указывается и имя БД

2024-03-29 07:41 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/service/AuthenticationService.java
> +    }
Изменил вот так. Думаю так наиболее логичным решение. 
```
public class AuthenticationServiceCommand {

    private final UserServiceCommand userServiceCommand;
    private final UserServiceQuery userServiceQuery;
    private final JwtService jwtService;

    public JwtAuthenticationResponse signup(SignUpRequest request) {
        var user = userServiceCommand.createUser(request);

        return jwtService.generateTokenAuthResponse(user);
    }

    public JwtAuthenticationResponse login(LoginRequest request) {
        var user = userServiceQuery.findByLogin(request.getLogin());

        return jwtService.generateTokenAuthResponse(user);
    }
}
```

2024-03-29 07:46 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/service/JwtService.java
> +    public String generateToken(UserDetails userDetails) {
Сейчас UserDetails реализован там, где это нужно. 

про фичи (fitch), не правильно написал) 
Имеется ввиду, что в дальнейшем мы будем использовать isEnabled() для юзера. Да и приписывание поидее происходит внутри UserDetails.

2024-03-29 08:21 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/controller/TestController.java
> +public class TestController {
Да, все поправил. Следуя инструкции Readme все запускается. Я стараюсь перед каждым коммитом проверить работает ли из докера приложение или нет.

2024-03-29 12:09 UTC, traktorlixach requested changes

2024-03-29 12:09 UTC, traktorlixach commented on README.md
> +          поле [token.secret.key](src/main/resources/application.properties) либо любой другой секретный ключ
- звучит как часть запуска приложения, если так, то стоило бы перенести туда
- а что это за ключ? уникальность серверного приложения, как часть фреймворка?
- вообще лучше от этого отказаться вовсе, все подобные штуки максимально должны быть обёрнуты в докере, то есть разворачивая проект пользователь должен только запустить контейнеры, и всё внутри должно отработать само. следует перенести это в Dockerfile

2024-03-29 12:09 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +                                        .requestMatchers(HttpMethod.GET, "/api/v1/test/**")
Лишний метод

2024-03-29 12:09 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/dto/SignUpRequest.java
> +    // создан соотвветсвущий пользователь
Проверь орфографию и с делай в одну строку

2024-03-29 12:09 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/dto/SignUpRequest.java
> +    // создан соотвветсвущий пользователь
И вообще суть коммента не ясна, о чём тут говорится?

2024-03-29 12:09 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/filters/JwtAuthenticationFilter.java
> +        filterChain.doFilter(request, response);
Разделяй немного пустыми строка по логическим блокам, сейчас нечитаемо

2024-03-29 12:09 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/filters/JwtAuthenticationFilter.java
> +        jwt = authHeader.substring(7);
Почему 7? Это необходимо вынести в константу класса

2024-03-29 12:09 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/repo/CustomUserDetailsService.java
> +
Лишняя строка, и в других классах тоже есть

2024-03-29 12:09 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/UserServiceCommand.java
> +/** Командный контроллер (для создания и обновления пользователя) */
Комментарий лишний, и в классе ниже тоже

2024-03-29 12:09 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/UserServiceQuery.java
> +        }
Репозиторий должен быть один, все юзеры в одной таблице, а тарологи/клиенты/стафф - это вспомогательные таблицы, связанные с таблицей юзеров связью 1к1. И находить пользователя нужно одним запросом к репозиторию юзеров. А уже в зависимости от наличия связи с одной из связанных таблиц должна гидрироваться та или иная модель. Как это сделать грамотно, пока не знаю, но ты можешь попробовать пока поискать в сторону дискриминатора в ORM

2024-03-29 12:09 UTC, traktorlixach commented on .env.dist
> +
так-то порт может быть разным от окружения к окружению, но если это не понадобится, то оставляем так, окей. если что, позже добавим

2024-03-29 12:09 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +        return authProvider;
Я вижу отхождение от такого правила с отступом в случае реально тонких методов, когда одна маленькая логическая структура сразу ведёт к возврату. Если же метод имеет несколько логических блоков, то их визуальная сепарация необходима. Если не нравится, то попробуй переписать методы тоньше и точнее, тогда можно вообще без пустых строк в методах)

2024-03-29 12:09 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/AuthenticationService.java
> +    }
Другое дело! Вот это можно считать почти образцовым классом.
Кстати, вот как раз пример, где методы настолько тонкие, что можно и обойтись без пустой строки перед return, если хочешь

2024-04-02 09:39 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/service/UserServiceQuery.java
> +        }
Я думал об этом, но возможно упорется туда хорошее количество времени, поэтому решил так сделать. Подумал, что менее читаемо будет. 
Я думал вынести в отдельный private метод просто эту логику, допустим да и все. И так-же тут нужно думать какое решение будет быстрее. Зачастую будут искаться клиенты, то есть зачем нам искать в taroter`ах и staff клиента. Так как основная задача будет быстрый поиск клиентов, то такой метод, как мне кажется достойный :)

2024-04-02 09:44 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/filters/JwtAuthenticationFilter.java
> +        jwt = authHeader.substring(7);
Тут из-за того что JWT передается в Baerer, это просто логика обработки и скорее всего никак меняться не будет. 
 ```
if (StringUtils.isEmpty(authHeader) || !StringUtils.startsWith(authHeader, "Bearer ")) {
            filterChain.doFilter(request, response);
            return;
        }
        ```

2024-04-02 10:03 UTC, yanisderbikov commented on README.md
> +          поле [token.secret.key](src/main/resources/application.properties) либо любой другой секретный ключ
Если все-таки это устанавливать в dockerfile то будет тратиться время. Не знаю на сколько рационально вообще оставлять инструкцию по созданию ключа. 
Думаю на сколько это нужно все-таки. В env.dist есть примерный секретный ключ, но можно использовать его для запуска указать любой другой, например "1"

2024-04-02 10:05 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/service/UserServiceCommand.java
> +/** Командный контроллер (для создания и обновления пользователя) */
Исправил

2024-04-02 10:06 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/filters/JwtAuthenticationFilter.java
> +        filterChain.doFilter(request, response);
Исправил

2024-04-02 10:06 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/dto/SignUpRequest.java
> +    // создан соотвветсвущий пользователь
Исправил

2024-04-02 10:06 UTC, yanisderbikov commented on src/main/java/com/vizhu/vizhu/config/WebSecurityConfig.java
> +                                        .requestMatchers(HttpMethod.GET, "/api/v1/test/**")
Исправил

2024-04-02 10:24 UTC, yanisderbikov commented on .gitignore
> -.vscode/
Исправил

2024-04-02 18:00 UTC, traktorlixach requested changes

2024-04-02 18:00 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/UserServiceQuery.java
> +        }
Давай тогда пока в приватный метод это вынесем, а я потом это сам переделаю красиво и тебе дам на ревью.
Пометь метод как TODO со ссылкой на задачу https://vizhu.youtrack.cloud/issue/VO-4

2024-04-02 18:00 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/service/JwtService.java
> +    public String generateToken(UserDetails userDetails) {
isEnabled - хорошо, но меня другие интересуют:
accountNonExpired  
accountNonLocked  
credentialsNonExpired  
Они зачем сейчас?

а fitch - это feature, нет?)

2024-04-02 18:00 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/filters/JwtAuthenticationFilter.java
> +        jwt = authHeader.substring(7);
Теперь строка "Bearer " нуждается в вынесение в константу класса)  
Можно поступить лучше - после проверки на существование "Bearer " в начале токена просто вырезай "Bearer " из строки токена. Не отрезай 7 символов, а вырезай именно то, что проверяешь, иначе однажды кто-то в этом коде может изменить одно и забыть изменить другое (ну может не здесь, а в аналогичной ситуации, но подход ты понял)

2024-04-02 18:00 UTC, traktorlixach commented on src/main/java/com/vizhu/vizhu/filters/JwtAuthenticationFilter.java
> +        jwt = authHeader.substring(7);
А вообще что-то я упустил.. зачем ты сам реализуешь проверку токена? Разве нет у org.springframework.security штатных классов работы с JWT и их валидации?
Да и к самому этому методу у меня много вопросов, но они подождут. Давай попробуем реализовать проверку токена с помощью библиотек вендора, наверняка это решалось миллионами доя нас)

2024-04-22 09:19 UTC, closed without merging